# OpenRouter API Configuration
# Get your API key from: https://openrouter.ai/keys
OPENROUTER_API_KEY = "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"

# Optional: Database configuration (SQLite is used by default)
DB_NAME = "medscript_pro.db"

# Optional: Application settings
APP_NAME = "MedScript Pro"
APP_VERSION = "1.0.0"

# Note: If you don't have an OpenRouter API key, the app will use fallback mode
# The fallback provides basic drug interaction checking without AI analysis