# Streamlit secrets file for local development and cloud deployment
# This file should be kept private and not committed to version control

GROQ_API_KEY = "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"
GROQ_MODEL = "gemma2-9b-it"
GROQ_MAX_TOKENS = "2048"
GROQ_TEMPERATURE = "0.1"
GROQ_TIMEOUT = "45"
DATABASE_NAME = "medscript_pro.db"
APP_ENV = "production"
DEBUG = "False"